# Copyright (c) 2021 SolarWinds, LLC.
# All rights reserved.

name: Ruby Gem to PackageCloud

on:
  workflow_dispatch:

jobs:
  build:
    name: Build + Publish to PackageCloud
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby 2.7 and bundle
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install gems
        run: |
          echo 'gem: --no-document' >> ~/.gemrc
          bundle install

      - name: Install swig 4.0.2
        run: |
          apt udate && apt install -y --no-install-recommends bison
          curl -SL https://github.com/swig/swig/archive/refs/tags/v4.0.2.tar.gz | tar xzC /tmp
          cd /tmp/swig-4.0.2
          ./autogen.sh && ./configure && make && sudo make install
          cd -

      - name: Grab current version
        id: version
        run: |
          echo "gem_version=`ruby -e 'require "./lib/solarwinds_otel_apm/version"; puts SolarWindsOTelAPM::Version::STRING'`" >> $GITHUB_OUTPUT

      - name: Build gem and publish to packagecloud
        id: gemstep
        run:  |
          bundle exec rake build_gem_push_to_packagecloud[${{ steps.version.outputs.gem_version }}]
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
