# Copyright (c) 2021 SolarWinds, LLC.
# All rights reserved.

name: Run Ruby Unit Test

on:
  # push:
  #   branches-ignore:
  #     - main
  #   paths-ignore:
  #     - 'test/Dockerfile_*'
  workflow_dispatch:

jobs:

  unit_test:
    name: ${{ matrix.os }} - ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.0.6'] # ['3.2.2','3.1.0','3.0.6','2.7.5']
        os: ['buster'] # ['buster', 'alpine3.17']

    container:
      image: ruby:${{ matrix.ruby }}-${{ matrix.os }}

    env:
      SW_APM_SERVICE_KEY: ${{ secret.DUMMY_SW_APM_SERVICE_KEY }}
      RUBY_VERSION: ${{ matrix.ruby }}

    steps:
    - name: Checkout ${{ github.ref }}
      uses: actions/checkout@v3

    - name: print some info
      run: |
        user=`whoami`
        pwd=`pwd`
        echo "User: $user"
        echo "Current dir: $pwd"
        echo "Home dir: $HOME"
        echo "Branch: ${GITHUB_REF#refs/*/}"

    - name: ruby tests
      run: |
        export HOME=/root
        version=`rbenv versions --bare | grep ${{ matrix.ruby }}`
        rbenv global $version
        echo "testing with ruby version: $version"
        test/test_setup.sh
