# Copyright (c) 2021 SolarWinds, LLC.
# All rights reserved.

name: Run Ruby Tests on Ubuntu

on:
  # push:
  #   branches-ignore:
  #     - main
  #   paths-ignore:
  #     - 'test/run_otel_tests/Dockerfile_*'
  workflow_dispatch:

jobs:

  ubuntu_test:
    name: ubuntu - ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.1', '3.0', '2.7', '2.6']

    container:
      image: ghcr.io/${{ github.repository }}/apm_ruby_ubuntu

    env:
      SW_APM_SERVICE_KEY: ${{ secret.DUMMY_SW_APM_SERVICE_KEY }}

    steps:
    - name: Checkout ${{ github.ref }}
      uses: actions/checkout@v3

    - name: print some info
      run: |
        user=`whoami`
        pwd=`pwd`
        echo "User: $user"
        echo "Current dir: $pwd"
        echo "Home dir: $HOME"
        echo "Branch: ${GITHUB_REF#refs/*/}"

    - name: ruby tests
      run: |
        export HOME=/root
        version=`rbenv versions --bare | grep ${{ matrix.ruby }}`
        rbenv global $version
        echo "testing with ruby version: $version"
        test/run_otel_tests/run_tests.sh -r $version
